#!/bin/bash

cat > views/landing.ejs << 'V1'
<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><%= title %></title><link rel="stylesheet" href="/assets/css/style.css"></head><body><nav class="navbar"><div class="container"><a href="/" class="logo">🎮 LUDO</a><div class="nav-links"><% if (user) { %><a href="/user/dashboard">Дашборд</a><a href="/quests">Квесты</a><a href="/community/leaderboard">Рейтинг</a><form action="/auth/logout" method="POST" style="display:inline"><button class="btn btn-sm">Выйти</button></form><% } else { %><a href="/quests">Квесты</a><a href="/auth/login">Войти</a><a href="/auth/register" class="btn btn-primary">Регистрация</a><% } %></div></div></nav><header class="hero"><div class="container"><h1 class="hero-title">🎮 Gamify Your World</h1><p class="hero-subtitle">Превращай привычки в увлекательные квесты</p><div class="hero-actions"><a href="/auth/register" class="btn btn-primary btn-lg">Начать бесплатно</a><a href="/quests" class="btn btn-secondary btn-lg">Посмотреть квесты</a></div></div></header><section class="features"><div class="container"><h2>Как это работает</h2><div class="features-grid"><div class="feature-card"><div class="icon">🎯</div><h3>Квесты вместо списков</h3><p>Превращай цели в увлекательные квесты с наградами и достижениями</p></div><div class="feature-card"><div class="icon">📊</div><h3>Отслеживай прогресс</h3><p>Смотри детальную статистику и празднуй свои победы</p></div><div class="feature-card"><div class="icon">🏆</div><h3>Зарабатывай XP</h3><p>Получай опыт, повышай уровень и открывай достижения</p></div><div class="feature-card"><div class="icon">👥</div><h3>Сообщество</h3><p>Вдохновляйся успехами других и соревнуйся в рейтинге</p></div><div class="feature-card"><div class="icon">🎓</div><h3>Эксперты</h3><p>Учись у профессионалов и проходи их авторские квесты</p></div><div class="feature-card"><div class="icon">🔥</div><h3>Система streak</h3><p>Поддерживай серии выполненных задач и не прерывай цепочку</p></div></div></div></section><footer class="footer"><div class="container"><p>&copy; 2026 LUDO. Made with ❤️</p></div></footer></body></html>
V1

cat > views/auth/login.ejs << 'V2'
<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><%= title %></title><link rel="stylesheet" href="/assets/css/style.css"></head><body><div class="auth-page"><div class="auth-card"><div class="auth-logo">🎮 LUDO</div><h1>Вход в систему</h1><% if (error) { %><div class="alert alert-error"><%= error %></div><% } %><form method="POST" action="/auth/login"><div class="form-group"><label>Email</label><input type="email" name="email" required class="form-control" placeholder="your@email.com"></div><div class="form-group"><label>Пароль</label><input type="password" name="password" required class="form-control" placeholder="••••••••"></div><button type="submit" class="btn btn-primary btn-block">Войти</button></form><p class="text-center mt-3">Нет аккаунта? <a href="/auth/register">Зарегистрируйтесь</a></p><p class="text-center"><a href="/">← На главную</a></p></div></div></body></html>
V2

cat > views/auth/register.ejs << 'V3'
<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><%= title %></title><link rel="stylesheet" href="/assets/css/style.css"></head><body><div class="auth-page"><div class="auth-card"><div class="auth-logo">🎮 LUDO</div><h1>Регистрация</h1><% if (error) { %><div class="alert alert-error"><%= error %></div><% } %><form method="POST" action="/auth/register"><div class="form-group"><label>Имя пользователя</label><input type="text" name="username" required class="form-control" placeholder="username"></div><div class="form-group"><label>Email</label><input type="email" name="email" required class="form-control" placeholder="your@email.com"></div><div class="form-group"><label>Пароль</label><input type="password" name="password" required class="form-control" placeholder="••••••••" minlength="6"></div><button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button></form><p class="text-center mt-3">Уже есть аккаунт? <a href="/auth/login">Войти</a></p><p class="text-center"><a href="/">← На главную</a></p></div></div></body></html>
V3

cat > views/user/dashboard.ejs << 'V4'
<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><%= title %></title><link rel="stylesheet" href="/assets/css/style.css"></head><body><%- include('../partials/navbar') %><div class="container dashboard"><div class="dashboard-header"><h1>Добро пожаловать, <%= user.username %>!</h1><p>Уровень <%= stats.level %> • <%= stats.xp %> XP</p></div><div class="stats-grid"><div class="stat-card"><div class="stat-icon">🎯</div><h3>Активных квестов</h3><p class="stat-number"><%= stats.active %></p></div><div class="stat-card"><div class="stat-icon">⚡</div><h3>XP</h3><p class="stat-number"><%= stats.xp %></p></div><div class="stat-card"><div class="stat-icon">🏆</div><h3>Уровень</h3><p class="stat-number"><%= stats.level %></p></div></div><div class="section"><h2>Активные квесты</h2><% if (userQuests.length > 0) { %><div class="quests-grid"><% userQuests.forEach(uq => { %><div class="quest-card"><h3><%= uq.quest.title %></h3><p><%= uq.quest.description.substring(0, 100) %>...</p><div class="progress-bar"><div class="progress-fill" style="width: <%= uq.progress %>%"></div></div><p class="progress-text"><%= uq.progress %>% завершено</p><div class="quest-meta"><span class="badge badge-<%= uq.quest.difficulty %>"><%= uq.quest.difficulty %></span><span>🔥 Streak: <%= uq.currentStreak %></span></div><a href="/quests/<%= uq.quest.id %>" class="btn btn-sm btn-primary">Продолжить</a></div><% }); %></div><% } else { %><div class="empty-state"><div class="empty-icon">🎯</div><p>У вас пока нет активных квестов</p><a href="/quests" class="btn btn-primary">Найти квест</a></div><% } %></div></div></body></html>
V4

cat > views/user/profile.ejs << 'V5'
<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><%= title %></title><link rel="stylesheet" href="/assets/css/style.css"></head><body><%- include('../partials/navbar') %><div class="container"><div class="profile-page"><div class="profile-header"><div class="profile-avatar"><% if (profile.avatarUrl) { %><img src="<%= profile.avatarUrl %>" alt="Avatar"><% } else { %><div class="avatar-placeholder"><%= profile.username.charAt(0).toUpperCase() %></div><% } %></div><div class="profile-info"><h1><%= profile.username %></h1><p class="profile-email"><%= profile.email %></p><div class="profile-stats"><span class="badge badge-level">Уровень <%= profile.level %></span><span class="badge badge-xp"><%= profile.xp %> XP</span><span class="badge badge-<%= profile.role %>"><%= profile.role %></span></div></div></div><div class="profile-sections"><div class="profile-section"><h2>О себе</h2><% if (profile.bio) { %><p><%= profile.bio %></p><% } else { %><p class="text-muted">Информация отсутствует</p><% } %></div><div class="profile-section"><h2>Статистика</h2><div class="stats-grid"><div class="stat-item"><span class="stat-label">Уровень</span><span class="stat-value"><%= profile.level %></span></div><div class="stat-item"><span class="stat-label">XP</span><span class="stat-value"><%= profile.xp %></span></div><div class="stat-item"><span class="stat-label">Подписка</span><span class="stat-value"><%= profile.subscriptionTier %></span></div></div></div><% if (profile.role === 'user') { %><div class="profile-section"><a href="/expert/apply" class="btn btn-secondary">Стать экспертом</a></div><% } %></div></div></div></body></html>
V5

cat > views/user/achievements.ejs << 'V6'
<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><%= title %></title><link rel="stylesheet" href="/assets/css/style.css"></head><body><%- include('../partials/navbar') %><div class="container"><h1>Мои достижения</h1><% if (achievements.length > 0) { %><div class="achievements-grid"><% achievements.forEach(ua => { %><div class="achievement-card achievement-<%= ua.achievement.rarity %>"><div class="achievement-icon"><%= ua.achievement.iconUrl || '🏆' %></div><h3><%= ua.achievement.name %></h3><p><%= ua.achievement.description %></p><span class="badge badge-<%= ua.achievement.rarity %>"><%= ua.achievement.rarity %></span><p class="achievement-date">Получено: <%= moment(ua.earnedAt).format('DD.MM.YYYY') %></p></div><% }); %></div><% } else { %><div class="empty-state"><div class="empty-icon">🏆</div><p>У вас пока нет достижений</p><p class="text-muted">Выполняйте квесты и получайте достижения!</p></div><% } %></div></body></html>
V6

echo "✅ Views 1/3 created"
